import React from 'react';

interface RegressionTestProps {
  regressionTest: string;
  pageNumber: number;
}

const PAGE_NUMBER_STYLE: React.CSSProperties = {
  position: 'absolute',
  bottom: '12mm',
  right: '16mm',
  fontSize: '9px',
  color: '#666666',
  fontFamily: 'monospace',
};

/** Simple tokenizer for TypeScript/JavaScript syntax highlighting in print */
function tokenizeLine(line: string): React.ReactNode[] {
  const tokens: React.ReactNode[] = [];
  const trimmed = line.trimStart();

  if (trimmed.startsWith('//')) {
    tokens.push(<span key="comment" className="syn-comment">{line}</span>);
    return tokens;
  }

  const keywords = /\b(import|from|test|expect|const|let|var|async|await|return|if|else|function|new|throw|try|catch|describe|it|beforeAll|afterAll|toBe|toContain|not)\b/g;
  const stringRegex = /('(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*"|`(?:[^`\\]|\\.)*`)/g;
  const combined = new RegExp(`(${stringRegex.source}|${keywords.source})`, 'g');
  let lastIndex = 0;
  let match: RegExpExecArray | null;

  while ((match = combined.exec(line)) !== null) {
    if (match.index > lastIndex) {
      tokens.push(<span key={`t-${lastIndex}`}>{line.slice(lastIndex, match.index)}</span>);
    }
    const value = match[0];
    if (value.startsWith("'") || value.startsWith('"') || value.startsWith('`')) {
      tokens.push(<span key={`s-${match.index}`} className="syn-string">{value}</span>);
    } else {
      tokens.push(<span key={`k-${match.index}`} className="syn-keyword">{value}</span>);
    }
    lastIndex = match.index + value.length;
  }

  if (lastIndex < line.length) {
    tokens.push(<span key={`r-${lastIndex}`}>{line.slice(lastIndex)}</span>);
  }

  return tokens.length > 0 ? tokens : [<span key="empty">{line || '\u00A0'}</span>];
}

export function RegressionTest({ regressionTest, pageNumber }: RegressionTestProps) {
  const MAX_LINES = 50;
  const originalLines = regressionTest.split('\n');
  const displayTest = originalLines.length > MAX_LINES
    ? originalLines.slice(0, MAX_LINES).join('\n') + 
      '\n\n// ... truncated for report. Full test in GitHub PR.'
    : regressionTest;

  const lines = displayTest.split('\n');

  return (
    <div className="report-page" style={{ background: '#ffffff', color: '#111111', position: 'relative' }}>
      <h2 className="report-section-heading">Automated Regression Test</h2>

      <p>
        The following Playwright test was auto-generated by VibeAudit.
        Add it to your test suite. It will fail if this vulnerability is reintroduced.
      </p>

      <div className="report-code-block" style={{
        marginBottom: '24px',
        pageBreakInside: 'avoid',
        breakInside: 'avoid',
        whiteSpace: 'pre-wrap',
        wordBreak: 'break-all',
        fontSize: '10px',
        lineHeight: '1.4',
        maxHeight: 'none',
        overflow: 'visible'
      }}>
        {lines.map((line, idx) => (
          <div key={idx} style={{ minHeight: '18px' }}>
            {tokenizeLine(line)}
          </div>
        ))}
      </div>

      <div style={{ marginBottom: '16px' }}>
        <h3 className="report-sub-heading">Run Command</h3>
        <div className="report-code-block" style={{ background: '#1a1a2e', color: '#e0e0e0', border: '1px solid #333' }}>
          $ npx playwright test vibeaudit-regression.spec.ts
        </div>
      </div>

      <div style={{ fontSize: '13px', color: '#333333', lineHeight: 1.8 }}>
        <div style={{ marginBottom: '8px' }}>
          <strong>Expected result:</strong> All assertions pass. Status 403 returned for cross-user resource access attempts.
        </div>
        <div style={{ color: '#c0392b' }}>
          <strong>Failure meaning:</strong> This vulnerability has been reintroduced. Immediate remediation required.
        </div>
      </div>

      <div style={PAGE_NUMBER_STYLE}>Page {pageNumber} of 9 — CONFIDENTIAL</div>
    </div>
  );
}
