import React from 'react';
import type { ReportData } from '@/types';
import { formatReportDate, formatDuration } from '../utils/redact';

interface ScanMetadataProps {
  data: ReportData;
  pageNumber: number;
}

const PAGE_NUMBER_STYLE: React.CSSProperties = {
  position: 'absolute',
  bottom: '12mm',
  right: '16mm',
  fontSize: '9px',
  color: '#666666',
  fontFamily: 'monospace',
};

export function ScanMetadata({ data, pageNumber }: ScanMetadataProps) {
  const { scanMeta, scanConfig } = data;
  const duration = scanMeta.endTime - scanMeta.startTime;

  const safeFormatDuration = (ms: number) => {
    if (!ms || ms === 0) return 'N/A';
    return formatDuration(ms);
  };

  const formatCount = (n: number) => (!n || n === 0) ? 'N/A' : String(n);

  // Vulnerabilities found ratio
  const endpointsDiscovered = scanMeta.endpointsDiscovered || 0;
  const endpointsTested = scanMeta.endpointsTested || 0;
  const vulnRatio = endpointsTested > 0
    ? `1 / ${endpointsTested} tested (${endpointsDiscovered} discovered)`
    : 'N/A';

  const rows: [string, string][] = [
    ['Scan ID', scanMeta.scanId],
    ['Target URL', scanConfig.targetUrl],
    ['Scan Started', formatReportDate(scanMeta.startTime)],
    ['Scan Completed', formatReportDate(scanMeta.endTime)],
    ['Duration', safeFormatDuration(duration)],
    ['Endpoints Discovered', formatCount(scanMeta.endpointsDiscovered)],
    ['Endpoints Tested', formatCount(scanMeta.endpointsTested)],
    ['Vulnerabilities Found', vulnRatio],
    ['Scanner Version', scanMeta.scannerVersion],
    ['Analysis Engine', scanMeta.aiModel],
    ['GitHub PR', scanMeta.prUrl || 'Not generated'],
  ];

  return (
    <div className="report-page" style={{ background: '#ffffff', color: '#111111', position: 'relative' }}>
      <h2 className="report-section-heading">Scan Metadata</h2>

      <table className="report-kv-table">
        <tbody>
          {rows.map(([label, value], i) => (
            <tr key={i} style={{ background: i % 2 === 1 ? '#fafafa' : '#ffffff' }}>
              <td>{label}</td>
              <td>{value}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div style={{
        marginTop: '60px',
        paddingTop: '20px',
        borderTop: '1px solid #e0e0e0',
        fontSize: '11px',
        color: '#888888',
        lineHeight: 1.6,
        fontStyle: 'italic',
        textAlign: 'center' as const,
      }}>
        <p>
          This report was generated by VibeAudit automated scanning tooling.
          All findings should be reviewed by a qualified security engineer
          before remediation is applied to production systems.
        </p>
        <p>
          VibeAudit does not guarantee the absence of additional vulnerabilities
          not covered by this scan.
        </p>
      </div>

      <div style={PAGE_NUMBER_STYLE}>Page {pageNumber} of 9 — CONFIDENTIAL</div>
    </div>
  );
}
