import { BOLAFinding, ScanConfig } from '../types';

export function generatePlaywrightTest(finding: BOLAFinding, config: ScanConfig): string {
  const endpoint = finding.endpoint;
  const resourceId = finding.victimResourceId;

  // Build dynamic assertions based on the sensitive fields actually found during the exploit
  const sensitiveFieldAssertions = finding.sensitiveFields
    .map((field) => `    expect(body.${field.key}).toBeUndefined();`)
    .join('\n');

  const sensitiveFieldComment = finding.sensitiveFields
    .map((field) => `//   - ${field.key} (${field.category})`)
    .join('\n');

  return `import { test, expect } from '@playwright/test';

// Security regression test — generated by VibeAudit
// Ensures BOLA vulnerability on ${endpoint} stays fixed
// If this test fails, the authorization check has been removed
//
// Sensitive fields that must NOT be exposed to non-owners:
${sensitiveFieldComment}

const emailB = process.env.TEST_USER_B_EMAIL;
const passwordB = process.env.TEST_USER_B_PASSWORD;

if (!emailB || !passwordB) {
  throw new Error(
    'TEST_USER_B_EMAIL and TEST_USER_B_PASSWORD must be set ' +
    'as environment variables before running generated tests. ' +
    'Never commit credentials.'
  );
}

test.describe('BOLA Regression: ${endpoint}', () => {
  test('attacker cannot access victim record ${resourceId}', async ({ request }) => {
    // Step 1: Authenticate as attacker (User B)
    const loginRes = await request.post('/api/auth/callback/credentials', {
      form: {
        email: emailB,
        password: passwordB,
        redirect: 'false',
        callbackUrl: '/',
        json: 'true',
      },
    });

    const cookies = loginRes.headers()['set-cookie'] || '';
    expect(cookies).toBeTruthy();

    // Step 2: Attempt to access victim's record using attacker session
    const attackRes = await request.get('${endpoint}', {
      headers: { Cookie: cookies },
    });

    // Step 3: Must return 403 Forbidden — not 200
    expect(attackRes.status()).toBe(403);

    // Step 4: Response body must not contain victim's sensitive data
    const body = await attackRes.json().catch(() => ({}));
${sensitiveFieldAssertions}
  });

  test('owner can still access their own record', async ({ request }) => {
    const emailA = process.env.TEST_USER_A_EMAIL;
    const passwordA = process.env.TEST_USER_A_PASSWORD;

    if (!emailA || !passwordA) {
      throw new Error(
        'TEST_USER_A_EMAIL and TEST_USER_A_PASSWORD must be set ' +
        'as environment variables before running generated tests. ' +
        'Never commit credentials.'
      );
    }

    // Step 1: Authenticate as victim (record owner)
    const loginRes = await request.post('/api/auth/callback/credentials', {
      form: {
        email: emailA,
        password: passwordA,
        redirect: 'false',
        callbackUrl: '/',
        json: 'true',
      },
    });

    const cookies = loginRes.headers()['set-cookie'] || '';
    expect(cookies).toBeTruthy();

    // Step 2: Access own record
    const res = await request.get('${endpoint}', {
      headers: { Cookie: cookies },
    });

    // Step 3: Owner should still get 200
    expect(res.status()).toBe(200);
  });
});
`;
}
